[project]
name = "realtime-etl-pipeline-on-aws"
version = "0.1"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "boto3>=1.39.17",
    "python-dotenv>=1.1.1",
]
